**Example:**

eggs = (1,3,8,3,2)

my_listComprehension = [1/egg for egg in eggs]

print(my_listComprehension)

# Insert here the module/library import statements

In [2]:
import math
import random
import os
import sys


# Calculate the square number of the first 20 numbers. Use square as the name of the list.
Remember to use list comprehensions and to print your results

In [7]:
square = [x ** 2 for x in range(20)]
square

[0,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361]

# Calculate the square root of the first 100 numbers. Use sqrt as the name of the list.
You will probably need to install math library with pip and import it in this file.

Remember to use list comprehensions and to print your results

In [1]:
sqrt = [math.sqrt(x) for x in range(100)]
sqrt

NameError: name 'math' is not defined


# Create this list [-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0]. Use my_list as the name of the list.
Remember to use list comprehensions and to print your results

In [11]:
my_list = [-x for x in reversed(range(11))]

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]


# Find the odd numbers from 1-100. Use odds as the name of the list. 
Remember to use list comprehensions and to print your results

In [17]:
odd = [ x for x in range(1,101) if x % 2 != 0]
odd

[1,
 3,
 5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49,
 51,
 53,
 55,
 57,
 59,
 61,
 63,
 65,
 67,
 69,
 71,
 73,
 75,
 77,
 79,
 81,
 83,
 85,
 87,
 89,
 91,
 93,
 95,
 97,
 99]

# Find all of the numbers from 1-1000 that are divisible by 7. Use divisible_by_seven as the name of the list.
Remember to use list comprehensions and to print your results

In [19]:
divisible_by_7 = [x for x in range(1,1001) if x % 7 == 0]
divisible_by_7

[7,
 14,
 21,
 28,
 35,
 42,
 49,
 56,
 63,
 70,
 77,
 84,
 91,
 98,
 105,
 112,
 119,
 126,
 133,
 140,
 147,
 154,
 161,
 168,
 175,
 182,
 189,
 196,
 203,
 210,
 217,
 224,
 231,
 238,
 245,
 252,
 259,
 266,
 273,
 280,
 287,
 294,
 301,
 308,
 315,
 322,
 329,
 336,
 343,
 350,
 357,
 364,
 371,
 378,
 385,
 392,
 399,
 406,
 413,
 420,
 427,
 434,
 441,
 448,
 455,
 462,
 469,
 476,
 483,
 490,
 497,
 504,
 511,
 518,
 525,
 532,
 539,
 546,
 553,
 560,
 567,
 574,
 581,
 588,
 595,
 602,
 609,
 616,
 623,
 630,
 637,
 644,
 651,
 658,
 665,
 672,
 679,
 686,
 693,
 700,
 707,
 714,
 721,
 728,
 735,
 742,
 749,
 756,
 763,
 770,
 777,
 784,
 791,
 798,
 805,
 812,
 819,
 826,
 833,
 840,
 847,
 854,
 861,
 868,
 875,
 882,
 889,
 896,
 903,
 910,
 917,
 924,
 931,
 938,
 945,
 952,
 959,
 966,
 973,
 980,
 987,
 994]

# Remove all of the vowels in a string. Hint: make a list of the non-vowels. Use non_vowels as the name of the list.
Remember to use list comprehensions and to print your results

In [38]:
# You can use the following test string but feel free to modify at your convenience

teststring = 'Find all of the words in a string that are monosyllabic'

In [39]:
vowels = 'aiueo'
non_vowels = [x for x in teststring if x not in vowels]
new_string = "".join(non_vowels)
new_string

'Fnd ll f th wrds n  strng tht r mnsyllbc'

# Find the capital letters (and not white space) in the sentence 'The Quick Brown Fox Jumped Over The Lazy Dog'. 
- **Use capital_letters as the name of the list.**

Remember to use list comprehensions and to print your results

In [42]:
pangram = 'The Quick Brown Fox Jumped Over The Lazy Dog'
capital_letters = [x for x in pangram if x.isupper() and x.isalpha()]
capital_letters

['T', 'Q', 'B', 'F', 'J', 'O', 'T', 'L', 'D']

# Find all the consonants in the sentence 'The quick brown fox jumped over the lazy dog'.
 - **Use consonants as the name of the list.**
 
Remember to use list comprehensions and to print your results.

In [45]:
pangram2 = 'The quick brown fox jumped over the lazy dog'
consonants = [x for x in pangram2 if x not in vowels and x.isalpha()]
consonants

['T',
 'h',
 'q',
 'c',
 'k',
 'b',
 'r',
 'w',
 'n',
 'f',
 'x',
 'j',
 'm',
 'p',
 'd',
 'v',
 'r',
 't',
 'h',
 'l',
 'z',
 'y',
 'd',
 'g']

# Find the folders you have in your madrid-oct-2018 local repo. Use files as name of the list.  

**Hint: You will probably need to import os library and some of its modules. You will need to make some online research.**

Remember to use list comprehensions and to print your results.

In [131]:
files = os.listdir('/mnt/c/Users/diego/classroom-materials')
files

['.git',
 '.gitignore',
 'Bienvenidos.pdf',
 'cheatsheets',
 'images',
 'README.md',
 'week_01']

# Create 4 lists of 10 random numbers between 0 and 100 each. Use random_lists as the name of the list. 
**Hint: You will probably need to import random module**

Remember to use list comprehensions and to print your results

In [3]:
random_lists = [[random.randint(0,100) for x in range(101)] for x in range(4)]
random_lists

[[61,
  98,
  40,
  93,
  69,
  55,
  34,
  70,
  55,
  52,
  12,
  13,
  36,
  7,
  42,
  82,
  29,
  63,
  47,
  46,
  86,
  96,
  69,
  81,
  2,
  91,
  90,
  72,
  3,
  42,
  89,
  51,
  35,
  42,
  55,
  54,
  29,
  89,
  0,
  63,
  76,
  16,
  81,
  16,
  7,
  28,
  29,
  85,
  80,
  11,
  90,
  26,
  74,
  23,
  7,
  22,
  26,
  27,
  74,
  41,
  76,
  100,
  56,
  4,
  55,
  78,
  5,
  100,
  31,
  79,
  9,
  80,
  10,
  99,
  11,
  56,
  99,
  40,
  52,
  74,
  45,
  31,
  11,
  84,
  36,
  86,
  4,
  64,
  64,
  1,
  90,
  81,
  80,
  36,
  10,
  42,
  64,
  6,
  74,
  1,
  46],
 [96,
  74,
  20,
  41,
  72,
  21,
  55,
  29,
  77,
  92,
  84,
  35,
  38,
  55,
  51,
  23,
  54,
  76,
  79,
  67,
  62,
  58,
  34,
  39,
  41,
  39,
  44,
  72,
  30,
  85,
  81,
  39,
  23,
  71,
  40,
  37,
  97,
  74,
  19,
  68,
  16,
  46,
  9,
  52,
  80,
  25,
  16,
  39,
  99,
  80,
  83,
  70,
  95,
  68,
  29,
  95,
  38,
  32,
  67,
  16,
  90,
  68,
  75,
  74,
  77,
  16,
  0,
  65,
  49,
  9,
  37,
  14,
  54,
  23,
  88,
  58,
  10,
  9,
  55,
  41,
  86,
  98,
  90,
  40,
  45,
  59,
  56,
  81,
  42,
  86,
  19,
  7,
  21,
  44,
  21,
  67,
  66,
  65,
  27,
  0,
  84],
 [19,
  97,
  7,
  88,
  12,
  42,
  51,
  77,
  28,
  40,
  43,
  16,
  14,
  10,
  77,
  23,
  89,
  19,
  23,
  61,
  41,
  35,
  42,
  40,
  1,
  27,
  95,
  9,
  22,
  83,
  34,
  3,
  49,
  98,
  81,
  4,
  79,
  91,
  66,
  35,
  15,
  40,
  7,
  52,
  38,
  83,
  96,
  56,
  33,
  55,
  94,
  79,
  72,
  1,
  61,
  36,
  2,
  39,
  100,
  17,
  20,
  5,
  70,
  13,
  37,
  70,
  51,
  65,
  21,
  3,
  79,
  57,
  32,
  55,
  47,
  87,
  10,
  64,
  42,
  77,
  24,
  22,
  21,
  60,
  18,
  15,
  98,
  13,
  21,
  22,
  13,
  50,
  58,
  52,
  3,
  9,
  9,
  28,
  56,
  83,
  14],
 [66,
  85,
  82,
  71,
  51,
  99,
  85,
  90,
  71,
  75,
  38,
  91,
  36,
  79,
  14,
  58,
  30,
  48,
  75,
  4,
  100,
  26,
  69,
  81,
  90,
  46,
  31,
  32,
  54,
  86,
  2,
  10,
  24,
  23,
  36,
  62,
  14,
  15,
  26,
  99,
  5,
  29,
  35,
  4,
  73,
  49,
  48,
  1,
  21,
  74,
  96,
  23,
  96,
  89,
  43,
  99,
  65,
  24,
  14,
  31,
  1,
  79,
  66,
  27,
  19,
  56,
  44,
  66,
  12,
  12,
  48,
  100,
  27,
  44,
  35,
  99,
  44,
  9,
  68,
  98,
  100,
  67,
  38,
  56,
  33,
  5,
  16,
  15,
  66,
  45,
  94,
  53,
  1,
  74,
  22,
  20,
  19,
  41,
  90,
  90,
  19]]

# Flatten the following list of lists. Use flatten_list as the name of the output.

Remember to use list comprehensions and to print your results

In [135]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]

In [136]:
flatten_list = [x for y in list_of_lists for x in y]
flatten_list

[1, 2, 3, 4, 5, 6, 7, 8, 9]


# Convert the numbers of the following nested list to floats. Use floats as the name of the list. 

Remember to use list comprehensions and to print your results.

In [73]:
list_of_lists = [['40', '20', '10', '30'], ['20', '20', '20', '20', '20', '30', '20'], \
['30', '20', '30', '50', '10', '30', '20', '20', '20'], ['100', '100'], ['100', '100', '100', '100', '100'], \
['100', '100', '100', '100']]

In [74]:
floats = [float(int(x)) for y in list_of_lists for x in y]
floats

[40.0,
 20.0,
 10.0,
 30.0,
 20.0,
 20.0,
 20.0,
 20.0,
 20.0,
 30.0,
 20.0,
 30.0,
 20.0,
 30.0,
 50.0,
 10.0,
 30.0,
 20.0,
 20.0,
 20.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0]

# Handle the exception thrown by the code below by using try and except blocks.

In [86]:
for i in ['a','b','c']:
    try:
        print(i**2)
    except TypeError:
        print('You cant square letters, dummy')

You cant square letters, dummy
You cant square letters, dummy
You cant square letters, dummy

# Handle the exception thrown by the code below by using try and except blocks. 

Then use a finally block to print 'All Done.'

Check in provided resources the type of error you may use.

In [91]:
x = 5
y = 0
try:
    z = x/y
except ZeroDivisionError:
    print('All done')

All done

# Handle the exception thrown by the code below by using try and except blocks. 

Check in provided resources the type of error you may use.

In [90]:
abc=[10,20,20]
try:
    print(abc[3])
except IndexError:
    print('that list doesnt have that many elements, dummy')

that list doesnt have that many elements, dummy

# Handle at least two kind of different exceptions when dividing a couple of numbers provided by the user. 

**Hint: take a look on python input function.**

Check in provided resources the type of error you may use.

In [64]:
number1 = input("Input a number: ")
number2 = input("Input another number: ")

try:
    float(number1)/float(number2)
except ZeroDivisionError:
        print('you cant divide by 0, dummy')
except ValueError:
        print('you cant divide letters, dummy')

Input a number:  a
Input another number:  5

you cant divide letters, dummy

# Handle the exception thrown by the code below by using try and except blocks. 

Check in provided resources the type of error you may use.

In [42]:
try:
    f = open('testfile','r')
    f.write('Test write this')
except FileNotFoundError:
    print('you dont have such file, dummy')

you dont have such file, dummy

# Handle the exceptions that can be thrown by the code below using try and except blocks. 

**Hint: the file could not exist and the data could not be convertable to int**

In [65]:
try:
    f = open('myfile.txt')
    line = f.readline()
    i = int(line.strip())
except FileNotFoundError:
    print('you dont have such file, dummy')
except ValueError:
    print('you cant convert that into an integer, dummy')

you dont have such file, dummy

# The following function can only run on a Linux system. 
The assert in this function will throw an exception if you call it on an operating system other than Linux.

Handle this exception using **try and except** blocks.

You will probably need to import sys

In [153]:
def linux_interaction():
    try:
        assert ('linux' in sys.platform), "Function can only run on Linux systems."
        print('Doing something.')
    except:
        print('Cant run this on anything other than linux, dummy')
linux_interaction()

Doing something.


# Bonus Questions:

You will need to make some research on dictionary comprehension to solve the following questions

## Write a function that asks for an integer and prints the square of it. 

**Hint: we need to continually keep checking until we get an integer.**

Use a while loop with a try,except, else block to account for incorrect inputs.

In [3]:
def isint():
    while True:
        try:
            num = int(input("Enter an integer: "))
            square = num ** 2
            return print(square)
        except:
            print("Please enter an integer")
    else:
        print('If you ever read this, the answer to life, the universe and everything is 42')
isint()

Enter an integer:  5

25


## Find all of the numbers from 1-1000 that are divisible by any single digit besides 1 (2-9). 

Use results as the name of the list

In [53]:
results = list(set([x for x in range(1,1001) for y in range(2,9) if x % y == 0 ]))
results

[2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 12,
 14,
 15,
 16,
 18,
 20,
 21,
 22,
 24,
 25,
 26,
 27,
 28,
 30,
 32,
 33,
 34,
 35,
 36,
 38,
 39,
 40,
 42,
 44,
 45,
 46,
 48,
 49,
 50,
 51,
 52,
 54,
 55,
 56,
 57,
 58,
 60,
 62,
 63,
 64,
 65,
 66,
 68,
 69,
 70,
 72,
 74,
 75,
 76,
 77,
 78,
 80,
 81,
 82,
 84,
 85,
 86,
 87,
 88,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 98,
 99,
 100,
 102,
 104,
 105,
 106,
 108,
 110,
 111,
 112,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 122,
 123,
 124,
 125,
 126,
 128,
 129,
 130,
 132,
 133,
 134,
 135,
 136,
 138,
 140,
 141,
 142,
 144,
 145,
 146,
 147,
 148,
 150,
 152,
 153,
 154,
 155,
 156,
 158,
 159,
 160,
 161,
 162,
 164,
 165,
 166,
 168,
 170,
 171,
 172,
 174,
 175,
 176,
 177,
 178,
 180,
 182,
 183,
 184,
 185,
 186,
 188,
 189,
 190,
 192,
 194,
 195,
 196,
 198,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 210,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 222,
 224,
 225,
 226,
 228,
 230,
 231,
 232,
 234,
 235,
 236,
 237,
 238,
 240,
 242,
 243,
 244,
 245,
 246,
 248,
 249,
 250,
 252,
 254,
 255,
 256,
 258,
 259,
 260,
 261,
 262,
 264,
 265,
 266,
 267,
 268,
 270,
 272,
 273,
 274,
 275,
 276,
 278,
 279,
 280,
 282,
 284,
 285,
 286,
 287,
 288,
 290,
 291,
 292,
 294,
 295,
 296,
 297,
 298,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 308,
 309,
 310,
 312,
 314,
 315,
 316,
 318,
 320,
 321,
 322,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 332,
 333,
 334,
 335,
 336,
 338,
 339,
 340,
 342,
 343,
 344,
 345,
 346,
 348,
 350,
 351,
 352,
 354,
 355,
 356,
 357,
 358,
 360,
 362,
 363,
 364,
 365,
 366,
 368,
 369,
 370,
 371,
 372,
 374,
 375,
 376,
 378,
 380,
 381,
 382,
 384,
 385,
 386,
 387,
 388,
 390,
 392,
 393,
 394,
 395,
 396,
 398,
 399,
 400,
 402,
 404,
 405,
 406,
 408,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 420,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 432,
 434,
 435,
 436,
 438,
 440,
 441,
 442,
 444,
 445,
 446,
 447,
 448,
 450,
 452,
 453,
 454,
 455,
 456,
 458,
 459,
 460,
 462,
 464,
 465,
 466,
 468,
 469,
 470,
 471,
 472,
 474,
 475,
 476,
 477,
 478,
 480,
 482,
 483,
 484,
 485,
 486,
 488,
 489,
 490,
 492,
 494,
 495,
 496,
 497,
 498,
 500,
 501,
 502,
 504,
 505,
 506,
 507,
 508,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 518,
 519,
 520,
 522,
 524,
 525,
 526,
 528,
 530,
 531,
 532,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 542,
 543,
 544,
 545,
 546,
 548,
 549,
 550,
 552,
 553,
 554,
 555,
 556,
 558,
 560,
 561,
 562,
 564,
 565,
 566,
 567,
 568,
 570,
 572,
 573,
 574,
 575,
 576,
 578,
 579,
 580,
 581,
 582,
 584,
 585,
 586,
 588,
 590,
 591,
 592,
 594,
 595,
 596,
 597,
 598,
 600,
 602,
 603,
 604,
 605,
 606,
 608,
 609,
 610,
 612,
 614,
 615,
 616,
 618,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 630,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 642,
 644,
 645,
 646,
 648,
 650,
 651,
 652,
 654,
 655,
 656,
 657,
 658,
 660,
 662,
 663,
 664,
 665,
 666,
 668,
 669,
 670,
 672,
 674,
 675,
 676,
 678,
 679,
 680,
 681,
 682,
 684,
 685,
 686,
 687,
 688,
 690,
 692,
 693,
 694,
 695,
 696,
 698,
 699,
 700,
 702,
 704,
 705,
 706,
 707,
 708,
 710,
 711,
 712,
 714,
 715,
 716,
 717,
 718,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 728,
 729,
 730,
 732,
 734,
 735,
 736,
 738,
 740,
 741,
 742,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 752,
 753,
 754,
 755,
 756,
 758,
 759,
 760,
 762,
 763,
 764,
 765,
 766,
 768,
 770,
 771,
 772,
 774,
 775,
 776,
 777,
 778,
 780,
 782,
 783,
 784,
 785,
 786,
 788,
 789,
 790,
 791,
 792,
 794,
 795,
 796,
 798,
 800,
 801,
 802,
 804,
 805,
 806,
 807,
 808,
 810,
 812,
 813,
 814,
 815,
 816,
 818,
 819,
 820,
 822,
 824,
 825,
 826,
 828,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 840,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 852,
 854,
 855,
 856,
 858,
 860,
 861,
 862,
 864,
 865,
 866,
 867,
 868,
 870,
 872,
 873,
 874,
 875,
 876,
 878,
 879,
 880,
 882,
 884,
 885,
 886,
 888,
 889,
 890,
 891,
 892,
 894,
 895,
 896,
 897,
 898,
 900,
 902,
 903,
 904,
 905,
 906,
 908,
 909,
 910,
 912,
 914,
 915,
 916,
 917,
 918,
 920,
 921,
 922,
 924,
 925,
 926,
 927,
 928,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 938,
 939,
 940,
 942,
 944,
 945,
 946,
 948,
 950,
 951,
 952,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 962,
 963,
 964,
 965,
 966,
 968,
 969,
 970,
 972,
 973,
 974,
 975,
 976,
 978,
 980,
 981,
 982,
 984,
 985,
 986,
 987,
 988,
 990,
 992,
 993,
 994,
 995,
 996,
 998,
 999,
 1000]

## Define a customised exception to handle not accepted values. 

You have the following user inputs and the Num_of_sections can not be less than 2.

**Hint: Create a class derived from the pre-defined Exception class in Python**

In [63]:
try:
    Total_Marks = int(input("Enter Total Marks Scored: ")) 
    Num_of_Sections = int(input("Enter Num of Sections: "))
except Exception:
    print('Whoops, seems like your input broke the code. Try entering only integers next time =)')

Enter Total Marks Scored:  5
Enter Num of Sections:  g

Whoops, seems like your input broke the code. Try entering only integers next time =)